# Generated by Django 5.2.17 on 2026-09-07 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_user'),
        ('complex', '0003_alter_apartment_apartment_type'),
        ('sales', '0002_sale_cancellation_reason_sale_cancelled_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='complex.apartment', verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='complex.apartment', verbose_name='Квартира'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('apartment',), name='one_active_booking_per_apartment'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(condition=models.Q(('is_cancelled', False)), fields=('apartment',), name='one_active_sale_per_apartment'),
        ),
    ]
