# Generated by Django 5.2.17 on 2026-09-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('payment_overdue', 'Просроченный платёж'), ('payment_today', 'Платёж сегодня'), ('booking_expiring', 'Бронь заканчивается'), ('budget_exceeded', 'Бюджет превышен'), ('new_sale', 'Новая продажа'), ('new_expense', 'Новый расход'), ('sale_cancelled', 'Продажа отменена'), ('record_deleted', 'Удаление записи'), ('info', 'Информация')], default='info', max_length=30),
        ),
    ]
