# Generated by Django 4.2.30 on 2026-06-24 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complex', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('unit', models.CharField(choices=[('kg', 'кг'), ('ton', 'тонна'), ('m', 'м'), ('m2', 'м²'), ('m3', 'м³'), ('piece', 'шт'), ('bag', 'мешок'), ('roll', 'рулон'), ('liter', 'литр'), ('box', 'коробка')], max_length=10, verbose_name='Ед. изм.')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='На складе')),
                ('min_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Мин. запас (предупреждение)')),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена за ед. ($)')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Поставщик')),
                ('phone', models.CharField(blank=True, max_length=25, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='Контактное лицо')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Приход'), ('out', 'Расход')], db_index=True, max_length=5, verbose_name='Тип')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Количество')),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена за ед. ($)')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма ($)')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Добавил')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_movements', to='complex.block', verbose_name='Блок/Объект')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='materials.material', verbose_name='Материал')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='materials.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Движение материала',
                'verbose_name_plural': 'Движения материалов',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='material',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='materials.supplier', verbose_name='Осн. поставщик'),
        ),
    ]
