# Generated by Django 4.2.30 on 2026-07-03 18:33

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/', validators=[core.validators.validate_document], verbose_name='Квитанция'),
        ),
    ]
