# Generated by Django 4.2.30 on 2026-06-24 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complex', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название бригады')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='complex.complex', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Бригада',
                'verbose_name_plural': 'Бригады',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=25, verbose_name='Телефон')),
                ('salary_type', models.CharField(choices=[('daily', 'Поденно'), ('monthly', 'Ежемесячно')], default='daily', max_length=10, verbose_name='Тип зарплаты')),
                ('salary_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ставка ($)')),
                ('hired_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата найма')),
                ('fired_date', models.DateField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активный')),
                ('passport_number', models.CharField(blank=True, max_length=50, verbose_name='Паспорт')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_workers', to=settings.AUTH_USER_MODEL, verbose_name='Добавил')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='workers.position', verbose_name='Должность')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='workers.team', verbose_name='Бригада')),
            ],
            options={
                'verbose_name': 'Рабочий',
                'verbose_name_plural': 'Рабочие',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Начало периода')),
                ('period_end', models.DateField(verbose_name='Конец периода')),
                ('days_worked', models.IntegerField(default=0, verbose_name='Отработано дней')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базовая сумма ($)')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Бонус ($)')),
                ('penalty', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Штраф ($)')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итого ($)')),
                ('is_paid', models.BooleanField(db_index=True, default=False, verbose_name='Выплачено')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Дата выплаты')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_payments_made', to=settings.AUTH_USER_MODEL, verbose_name='Выплатил')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to='workers.worker', verbose_name='Рабочий')),
            ],
            options={
                'verbose_name': 'Выплата зарплаты',
                'verbose_name_plural': 'Выплаты зарплат',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('status', models.CharField(choices=[('present', 'Присутствует'), ('absent', 'Отсутствует'), ('half', 'Полдня'), ('sick', 'Болен')], default='present', max_length=10, verbose_name='Статус')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Записал')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='workers.worker', verbose_name='Рабочий')),
            ],
            options={
                'verbose_name': 'Посещаемость',
                'verbose_name_plural': 'Посещаемость',
                'ordering': ['-date'],
                'unique_together': {('worker', 'date')},
            },
        ),
    ]
