# Generated by Django 4.2.30 on 2026-06-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='new_value',
            field=models.TextField(blank=True, verbose_name='Новое значение'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='old_value',
            field=models.TextField(blank=True, verbose_name='Старое значение'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Вход'), ('logout', 'Выход'), ('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление'), ('cancel', 'Отмена'), ('view', 'Просмотр'), ('export', 'Экспорт')], max_length=20, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='model_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID объекта'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-timestamp'], name='audit_audit_action_e33994_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model_name', 'object_id'], name='audit_audit_model_n_20c0d3_idx'),
        ),
    ]
