# Generated by Django 4.2.30 on 2026-06-23 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('phone', models.CharField(max_length=25, verbose_name='Телефон')),
                ('interested_in', models.CharField(blank=True, max_length=200, verbose_name='Интерес')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Бюджет ($)')),
                ('source', models.CharField(choices=[('office', 'Офис'), ('call', 'Звонок'), ('instagram', 'Instagram'), ('referral', 'Знакомые'), ('advertising', 'Реклама'), ('website', 'Сайт'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Источник')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('thinking', 'Думает'), ('callback', 'Перезвонить'), ('negotiation', 'Переговоры'), ('booked', 'Забронировал'), ('bought', 'Купил'), ('refused', 'Отказался')], default='new', max_length=20, verbose_name='Статус')),
                ('next_contact_date', models.DateField(blank=True, null=True, verbose_name='Следующий контакт')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Лид',
                'verbose_name_plural': 'Лиды (потенциальные покупатели)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=25, verbose_name='Телефон')),
                ('phone2', models.CharField(blank=True, max_length=25, verbose_name='Доп. телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('passport_series', models.CharField(blank=True, max_length=20, verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(blank=True, max_length=20, verbose_name='Номер паспорта')),
                ('passport_issued_by', models.CharField(blank=True, max_length=300, verbose_name='Кем выдан')),
                ('passport_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_clients', to=settings.AUTH_USER_MODEL, verbose_name='Добавил')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-created_at'],
            },
        ),
    ]
