# Generated by Django 4.2.30 on 2026-06-23 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название блока')),
                ('budget_planned', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Плановый бюджет ($)')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Блок',
                'verbose_name_plural': 'Блоки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Complex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Жилой комплекс',
                'verbose_name_plural': 'Жилые комплексы',
            },
        ),
        migrations.CreateModel(
            name='ConstructionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('foundation', 'Фундамент'), ('frame', 'Каркас'), ('walls', 'Стены'), ('roof', 'Крыша'), ('windows', 'Окна'), ('facade', 'Фасад'), ('utilities', 'Коммуникации'), ('interior', 'Внутренняя отделка'), ('completed', 'Завершено')], max_length=30, verbose_name='Этап')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В процессе'), ('completed', 'Завершено'), ('paused', 'Приостановлено')], default='pending', max_length=20, verbose_name='Статус')),
                ('progress', models.IntegerField(default=0, verbose_name='Прогресс (%)')),
                ('responsible', models.CharField(blank=True, max_length=200, verbose_name='Ответственный')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('note', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='complex.block', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Этап строительства',
                'verbose_name_plural': 'Этапы строительства',
                'unique_together': {('block', 'stage')},
            },
        ),
        migrations.CreateModel(
            name='PhotoReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='construction/', verbose_name='Фото')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='Подпись')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='complex.block', verbose_name='Блок')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='complex.constructionstage', verbose_name='Этап')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Фотоотчёт',
                'verbose_name_plural': 'Фотоотчёты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер этажа')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='complex.block', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Этаж',
                'verbose_name_plural': 'Этажи',
                'ordering': ['number'],
                'unique_together': {('block', 'number')},
            },
        ),
        migrations.AddField(
            model_name='block',
            name='complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='complex.complex', verbose_name='Комплекс'),
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер квартиры')),
                ('apartment_type', models.CharField(choices=[('1', '1-комнатная'), ('2', '2-комнатная'), ('3', '3-комнатная'), ('4', '4-комнатная'), ('studio', 'Студия'), ('penthouse', 'Пентхаус')], max_length=20, verbose_name='Тип')),
                ('area', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Площадь (м²)')),
                ('price_per_sqm', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена за м² ($)')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Общая цена ($)')),
                ('status', models.CharField(choices=[('free', 'Свободна'), ('booked', 'Забронирована'), ('sold', 'Продана'), ('unavailable', 'Недоступна')], default='free', max_length=20, verbose_name='Статус')),
                ('layout_image', models.ImageField(blank=True, null=True, upload_to='layouts/', verbose_name='Планировка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='complex.floor', verbose_name='Этаж')),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
                'ordering': ['floor__number', 'number'],
            },
        ),
    ]
