# Generated by Django 4.2.30 on 2026-07-03 18:33

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='layout_image',
            field=models.ImageField(blank=True, null=True, upload_to='layouts/', validators=[core.validators.validate_image], verbose_name='Планировка'),
        ),
        migrations.AlterField(
            model_name='photoreport',
            name='photo',
            field=models.ImageField(upload_to='construction/', validators=[core.validators.validate_image], verbose_name='Фото'),
        ),
    ]
