# Generated by Django 5.2.17 on 2026-09-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complex', '0002_alter_apartment_layout_image_alter_photoreport_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='apartment_type',
            field=models.CharField(choices=[('1', '1-комнатная'), ('2', '2-комнатная'), ('3', '3-комнатная'), ('4', '4-комнатная'), ('studio', 'Студия'), ('penthouse', 'Пентхаус'), ('commercial', 'Магазин / коммерция')], max_length=20, verbose_name='Тип'),
        ),
    ]
