# Generated by Django 4.2.30 on 2026-06-23 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('materials', 'Материалы'), ('salary', 'Зарплата'), ('equipment', 'Техника'), ('transport', 'Транспорт'), ('documents', 'Документы'), ('taxes', 'Налоги'), ('utilities', 'Коммунальные'), ('other', 'Прочее')], max_length=20, verbose_name='Категория')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма ($)')),
                ('date', models.DateField(verbose_name='Дата')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('document', models.FileField(blank=True, null=True, upload_to='expense_docs/', verbose_name='Документ/Чек')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Добавил')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='complex.block', verbose_name='Блок')),
                ('complex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='complex.complex', verbose_name='Комплекс')),
            ],
            options={
                'verbose_name': 'Расход',
                'verbose_name_plural': 'Расходы',
                'ordering': ['-date'],
            },
        ),
    ]
