# Generated by Django 4.2.30 on 2026-07-03 18:33

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='expense_docs/', validators=[core.validators.validate_document], verbose_name='Документ/Чек'),
        ),
    ]
